Prestamos-P2P/MVC_Presentacion/Controllers/HomeSolicitanteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Presentacion.ServicioImportacionesRef;

namespace MVC_Presentacion.Controllers
{
    public class HomeSolicitanteController : CommonController
    {
        public ActionResult Index()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Solicitante.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }



            return View("VerHomeSolicitante");
        }

        public ActionResult VerHomeSolicitante()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Solicitante.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }


            return View();
        }

        public ActionResult BuscarProyectos()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Solicitante.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }



            //TODOMDA: agregar vista de busqueda con filtros para solicitantes
            return RedirectToAction("Index", "BusquedaDeProyectos");
        }
    }
}

Prestamos-P2P/MVC_Presentacion/Views/HomeSolicitante/VerHomeSolicitante.cshtml
@{
    ViewBag.Title = "VerHomeSolicitante";
}

<h2>Home Solicitante</h2>

<br />
<div class="list-group">
    <div class="list-group-item">
        <p>Importar usuarios a la base de datos via documento de texto:</p>
        <button onclick="location.href='@Url.Action("ImportarUsuarios", "Common")';return false;" class="btn btn-default">Importar Usuarios</button>
    </div>

    <div class="list-group-item">
        <p>Importar proyectos a la base de datos via documento de texto:</p>
        <button onclick="location.href='@Url.Action("ImportarProyectos", "Common")';return false;" class="btn btn-default">Importar Proyectos</button>
    </div>

    <div class="list-group-item">
        <p>Buscar proyectos propuestos anteriormente:</p>
        <button onclick="location.href='@Url.Action("BuscarProyectos", "HomeSolicitante")';return false;" class="btn btn-default">Buscar Proyectos</button>
    </div>

    <div class="list-group-item">
        <button onclick="location.href='@Url.Action("Logout", "Common")';return false;" class="btn btn-default">Logout</button>
    </div>
</div>