Prestamos-P2P/MVC_Presentacion/Controllers/HomeInversorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Presentacion.ServicioImportacionesRef;

namespace MVC_Presentacion.Controllers
{
    public class HomeInversorController : CommonController
    {
        public ActionResult Index()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Inversor.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }

            return View("VerHomeInversor");
        }

        public ActionResult VerHomeInversor()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Inversor.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }



            return View();
        }

        public ActionResult BuscarProyectos()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Inversor.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }

            //TODOMDA: agregar vista de busqueda con filtros para inversores
            return RedirectToAction("Index", "BusquedaDeProyectos");
        }

        public ActionResult VerFinanciaciones()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.Inversor.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }



            //TODOMDA: agregar vista de financiaciones de este inversor
            return RedirectToAction("Index", "VerFinanciaciones");
        }

    }
}

Prestamos-P2P/MVC_Presentacion/Views/HomeInversor/VerHomeInversor.cshtml
@{
    ViewBag.Title = "VerHomeInversor";
}

<h2>Home Inversor</h2>

<br />
<div class="list-group">
    <div class="list-group-item">
        <p>Importar usuarios a la base de datos via documento de texto:</p>
        <button onclick="location.href='@Url.Action("ImportarUsuarios", "Common")';return false;" class="btn btn-default">Importar Usuarios</button>
    </div>

    <div class="list-group-item">
        <p>Importar proyectos a la base de datos via documento de texto:</p>
        <button onclick="location.href='@Url.Action("ImportarProyectos", "Common")';return false;" class="btn btn-default">Importar Proyectos</button>
    </div>

    <div class="list-group-item">
        <p>Buscar proyectos para financiar:</p>
        <button onclick="location.href='@Url.Action("BuscarProyectos", "HomeInversor")';return false;" class="btn btn-default">Buscar Proyectos</button>
    </div>

    <div class="list-group-item">
        <p>Ver todas las financiaciones a proyectos de este inversor:</p>
        <button onclick="location.href='@Url.Action("VerFinanciaciones", "HomeInversor")';return false;" class="btn btn-default">Ver Financiaciones</button>
    </div>

    <div class="list-group-item">
        <button onclick="location.href='@Url.Action("Logout", "Common")';return false;" class="btn btn-default">Logout</button>
    </div>
</div>