Prestamos-P2P/MVC_Presentacion/Controllers/HomeSinRegistrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Presentacion.ServicioImportacionesRef;

namespace MVC_Presentacion.Controllers
{
    public class HomeSinRegistrarController : CommonController
    {
        // GET: HomeSinRegistrar
        public ActionResult Index()
        {
            // para cuando entra por primera vez a la pagina
            if (Session["tipoDeUsuario"] == null)
            {
                Session["tipoDeUsuario"] = TiposDeUsuario.E_Nav.NoRegistrado;
            }
            return View("VerHomeSinRegistrar");
        }

        public ActionResult VerHomeSinRegistrar()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.NoRegistrado.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }


            return View();
        }

        public ActionResult IrARegistrarInversor()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.NoRegistrado.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }


            return RedirectToAction("Index", "InversorRegistration");
        }

        public ActionResult IrALogin()
        {
            /*security check*/
            if (Session["tipoDeUsuario"] == null)
            {
                return RedirectToAction("Logout", "Common");
            }
            else if (Session["tipoDeUsuario"].ToString() != TiposDeUsuario.E_Nav.NoRegistrado.ToString())
            {
                return RedirectToAction("Logout", "Common");
            }



            return RedirectToAction("Index", "Login");
        }
    }
}

Prestamos-P2P/MVC_Presentacion/Views/HomeSinRegistrar/VerHomeSinRegistrar.cshtml
@{
    ViewBag.Title = "VerHomeSinRegistrar";
}

<h2>Home</h2>

<br />
<div class="list-group">
    <div class="list-group-item">
        <p>Importar usuarios a la base de datos via documento de texto:</p>
        <button onclick="location.href='@Url.Action("ImportarUsuarios", "Common")';return false;" class="btn btn-default">Importar Usuarios</button>
    </div>

    <div class="list-group-item">
        <p>Importar proyectos a la base de datos via documento de texto:</p>
        <button onclick="location.href='@Url.Action("ImportarProyectos", "Common")';return false;" class="btn btn-default">Importar Proyectos</button>
    </div>

    <div class="list-group-item">
        <p>Registrar un nuevo inversor en la base de datos:</p>
        <button onclick="location.href='@Url.Action("IrARegistrarInversor", "HomeSinRegistrar")';return false;" class="btn btn-default">Registrar Inversor</button>
    </div>

    <div class="list-group-item">
        <p>Ingresar como usuario previamente registrado:</p>
        <button onclick="location.href='@Url.Action("IrALogin", "HomeSinRegistrar")';return false;" class="btn btn-default">Ingresar</button>
    </div>
</div>